stages:
  - build

#ANDROID BUILD - BUILDS APK
android:
  stage: build
  image: suyuemu/cibuild:android-x64
  script:
    - apt-get update -y
    - git submodule update --init --recursive
    - cd externals/vcpkg
    - git fetch --unshallow || true
    - cd ../..
    - export ANDROID_HOME="/usr/lib/android-sdk/"
    - echo y | sdkmanager --sdk_root=/usr/lib/android-sdk --licenses
    - bash ./.ci/scripts/android/build.sh
    - bash ./.ci/scripts/android/upload.sh
  artifacts:
    paths:
      - artifacts/*
  tags:
    - Linux
    - Parallelized
    - Testing
