stages:
  - format
  - build

clang-format:
  stage: format
  image: suyuemu/cibuild:linux-x64
  allow_failure: true
  variables:
    RELEASE_NAME: mainline
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/format/script.sh

build-linux:
  stage: build
  image: suyuemu/cibuild:linux-x64
  resource_group: linux-ci
  variables:
    RELEASE_NAME: mainline
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/linux/docker.sh
    - bash .ci/scripts/linux/upload.sh
  artifacts:
    paths:
      - artifacts/*

build-windows:
  stage: build
  image: suyuemu/cibuild:windows-x64
  resource_group: windows-ci
  variables:
    RELEASE_NAME: mainline
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/windows/docker.sh
    - bash .ci/scripts/windows/upload.sh
  artifacts:
    paths:
      - artifacts/*
